"""empty message

Revision ID: 7c06900931fe
Revises: 7525e5b44531
Create Date: 2026-05-24 19:27:38.840986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c06900931fe'
down_revision: Union[str, Sequence[str], None] = '7525e5b44531'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardtable', sa.Column('modify_date', sa.DateTime(), nullable=True))
    op.add_column('commenttable', sa.Column('modify_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commenttable', 'modify_date')
    op.drop_column('boardtable', 'modify_date')
    # ### end Alembic commands ###
